=== ESTG-PEI/2020-2021/XML_XSD/Exemplo5/Exemplo5.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" elementFormDefault="qualified">
    
    <xs:complexType name = "infoPessoa"> <!-- tipo global (podem ser reutilizados) -->
        <xs:sequence> <!-- Indicador de ordem -->
            <xs:element name = "primeiroNome" type = "xs:string" />
            <xs:element name = "ultimoNome" type = "xs:string" />
        </xs:sequence>
        <!-- Atributo com restrição em que pode ser M ou F -->
        <xs:attribute name = "genero" type = "tipoGenero" />
    </xs:complexType>
    
    <xs:simpleType name="tipoGenero">
        <xs:restriction base = "xs:string">
            <xs:enumeration value="M" />
            <xs:enumeration value="F" />
        </xs:restriction>
    </xs:simpleType>
    
    <!-- Elemento root -->
    <xs:element name = "pessoas">
        <xs:complexType>
            <xs:sequence minOccurs="1" maxOccurs="unbounded">
                <xs:element name = "pessoa" type = "infoPessoa"/>
            </xs:sequence>
        </xs:complexType>
    </xs:element>
</xs:schema>

=== ESTG-PEI/2020-2021/XML_XSD/Exemplo5/Exemplo5.xml
<?xml version="1.0" encoding="UTF-8"?>
<pessoas xmlns:xsi = "http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation = "Exemplo5.xsd">
    <pessoa genero = "M">
        <primeiroNome>Bruno</primeiroNome>
        <ultimoNome>Oliveira</ultimoNome>
    </pessoa>
    <pessoa genero = "M">
        <primeiroNome>Bruno</primeiroNome>
        <ultimoNome>Oliveira</ultimoNome>
    </pessoa>
    <pessoa genero = "M">
        <primeiroNome>Bruno</primeiroNome>
        <ultimoNome>Oliveira</ultimoNome>
    </pessoa>
</pessoas>
